pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - check-success=Lint
      - check-success=Add changeset to Dependabot updates
    actions:
      merge:
        method: squash