#!/usr/bin/env node

/**
 * Generates a TypeScript file containing version and build information
 * that can be imported by the application.
 */

import fs from "fs";
import path from "path";

const __dirname = path.dirname(new URL(import.meta.url).pathname);

// Read package.jsons
const packageJson = JSON.parse(
    fs.readFileSync(path.join(__dirname, "..", "package.json"), "utf8"),
);

// Determine server mode from NODE_ENV
// Default to 'production' if NODE_ENV is not set or is set to 'production'
const isDev = process.env.NODE_ENV === "development";
const serverMode = isDev ? "development" : "production";

// Generate TypeScript file content
const content = `// This file is auto-generated by scripts/generate-version.ts
// Do not edit manually

export const APP_VERSION = '${packageJson.version}';
export const SERVER_MODE: 'development' | 'production' = '${serverMode}';
`;

// Write to src/lib/version.ts
const outputPath = path.join(__dirname, "..", "src", "lib", "version.ts");
fs.writeFileSync(outputPath, content, "utf8");

console.log(
    `✓ Generated version info: v${packageJson.version} (${serverMode})`,
);
