#!/usr/bin/env node

/**
 * Generates a TypeScript file containing version and build information
 * that can be imported by the application.
 */

const fs = require('fs');
const path = require('path');

// Read package.json
const packageJson = JSON.parse(
  fs.readFileSync(path.join(__dirname, '..', 'package.json'), 'utf8')
);

// Determine server mode from NODE_ENV
const isDev = process.env.NODE_ENV !== 'production';
const serverMode = isDev ? 'development' : 'production';

// Generate TypeScript file content
const content = `// This file is auto-generated by scripts/generate-version.js
// Do not edit manually

export const APP_VERSION = '${packageJson.version}';
export const SERVER_MODE = '${serverMode}';
export const BUILD_TIME = '${new Date().toISOString()}';
`;

// Write to src/lib/version.ts
const outputPath = path.join(__dirname, '..', 'src', 'lib', 'version.ts');
fs.writeFileSync(outputPath, content, 'utf8');

console.log(`✓ Generated version info: v${packageJson.version} (${serverMode})`);
