name: Release

on:
    push:
        branches:
            - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    release:
        name: Release
        if: github.repository == 'notthebestdev/geo-invaders'
        runs-on: ubuntu-latest
        timeout-minutes: 20
        permissions:
            contents: write
            issues: write
            pull-requests: write
            id-token: write
        steps:
            - uses: actions/checkout@v6

            - name: Setup Node.js 20.x
              uses: actions/setup-node@v6
              with:
                  node-version: 20.x
                  cache: npm

            - name: Install Dependencies
              run: npm ci --prefer-offline

            - name: Create Release Pull Request
              uses: changesets/action@v1.5.3
              with:
                  commit: ':bookmark: ci(repo): Version packages'
                  title: ':bookmark: ci(repo): Version packages'
                  version: "npx changeset version"
                  publish: ""
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
